### PR TITLE
Serioushaircut error memo in a row

### PR DESCRIPTION
**Pull request by phoet**
@serioushaircut this would cover your case, right?

i still think that you should not rely on instance-variables to do the memoization.
if you would open an issue here or ask on stack-overflow, i would tell you that you are holding it wrong.

### CODE REVIEW

**Comment by phoet** [comment]
for reference https://github.com/phoet/memo-it/pull/13

**Review by serioushaircut — COMMENTED** [review]
Okay, that makes it very clear.

**Comment by serioushaircut** [comment]
> i still think that you should not rely on instance-variables to do the memoization.

Btw, I totally agree that it is nicer to capture any memo in its own 'method' with its own local context. But the example I gave is not limited to an instance variable, it could be *anything that is not in the binding from which the memo is generated*:
```
db_call ? memo { rest_call } : memo { other_rest_call }
```
would fail on second invocation if the db_call() returns a different value.
People do this.

This PR is a very good solution, though. Thx.

**Review by serioushaircut — APPROVED** [review]
If I may, I certainly approve.

**Comment by phoet** [comment]
i pushed a new version 0.5.0 with those changes

**Pull request merged**
